version: '3'
services: 
    cassandra-node1:
        image: cassandra:latest
        container_name: node1
        hostname: node1
        volumes:
            - ./tagsdb_node1:/var/lib/cassandra
            #- ./cassandra.yaml:/etc/cassandra/cassandra.yaml
        ports:
            - "9042:9042"
        environment:
            - "MAX_HEAP_SIZE=256M"
            - "HEAP_NEWSIZE=128M"
            - CASSANDRA_SEEDS=node1
            - CASSANDRA_START_RPC=false
            - CASSANDRA_CLUSTER_NAME=tagging_service_cluster
            - CASSANDRA_NUM_TOKENS=3
            - CASSANDRA_DC=DC1
            - CASSANDRA_RACK=RAC1
        restart: always
    cassandra-load-keyspace:
        container_name: tagging-service-cassandra-load-keyspace
        image: cassandra:latest
        depends_on:
            - cassandra-node1
            - cassandra-node2
            - cassandra-node3
        volumes:
            - ./tagsdb.cql:/tagsdb.cql 
        command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra-node1 -f /tagsdb.cql"
    cassandra-node2:
        image: cassandra:latest
        container_name: node2
        hostname: node2
        volumes:
            - ./tagsdb_node2:/var/lib/cassandra
        ports:
            - "9043:9042"
        environment:
            - "MAX_HEAP_SIZE=256M"
            - "HEAP_NEWSIZE=128M"
            - CASSANDRA_SEEDS=node1
            - CASSANDRA_START_RPC=false
            - CASSANDRA_CLUSTER_NAME=tagging_service_cluster
            - CASSANDRA_NUM_TOKENS=3
            - CASSANDRA_DC=DC2
            - CASSANDRA_RACK=RAC1
        restart: always
        depends_on:
            - cassandra-node1
    cassandra-node3:
        image: cassandra:latest
        container_name: node3
        hostname: node3
        volumes:
            - ./tagsdb_node3:/var/lib/cassandra
        ports:
            - "9044:9042"
        environment:
            - "MAX_HEAP_SIZE=256M"
            - "HEAP_NEWSIZE=128M"
            - CASSANDRA_SEEDS=node1
            - CASSANDRA_START_RPC=false
            - CASSANDRA_CLUSTER_NAME=tagging_service_cluster
            - CASSANDRA_NUM_TOKENS=3
            - CASSANDRA_DC=DC1
            - CASSANDRA_RACK=RAC1
        restart: always
        depends_on:
            - cassandra-node1